apiVersion: "v1"
kind: "Pod"
metadata:
  labels:
    label: "hub-cli"
spec:
  containers:
  - image: "tianon/github-hub:2.6"
    name: "hub"
    env:
    - name: "GITHUB_TOKEN"
      valueFrom:
        secretKeyRef:
          key: "GITHUB_TOKEN"
          name: "gh-token"
          optional: false