apiVersion: "v1"
kind: "Pod"
metadata:
  labels:
    label: "hub-cli"
spec:
  containers:
  - env:
    - name: "GITHUB_TOKEN"
      valueFrom:
        secretKeyRef:
          key: "GITHUB_TOKEN"
          name: "gh-token"
          optional: false
    image: "tianon/github-hub:latest"
    name: "hub"
    resources:
  - env:
    - name: "GITHUB_TOKEN"
      valueFrom:
        secretKeyRef:
          key: "GITHUB_TOKEN"
          name: "gh-token"
          optional: false