apiVersion: "v1"
kind: "Pod"
metadata:
  labels:
    label: "iq-server-cli"
spec:
  containers:
  - image: "sonatype/nexus-iq-server:1.103.0"
    name: "iq-cli"
    args:
    - "cat"
    command:
    - "/bin/sh"
    - "-c"
