apiVersion: v1
kind: Pod
metadata:
  labels:
    label: mvn
spec:
  containers:
  - name: maven
    image: maven:3.6-jdk-11-openj9
    command:
    - cat
    tty: true
    resources:
      requests:
        memory: "1000Mi"
        cpu: "500m"
    volumeMounts:
      - mountPath: "/usr/share/maven/ref"
        name: settings-xml
        readOnly: true
      - mountPath: "/root/.m2"
        name: mvn-pv-claim
  volumes:
    - name: settings-xml
      secret:
        secretName: settings-xml
    - name: mvn-pv-claim
      persistentVolumeClaim:
        claimName: mvn-pv-claim